---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  labels: 
    pvc: pgdata
  namespace: gb5
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-ceph-hdd-gz1

