---
apiVersion: v1
kind: Service
metadata:
  name: kubedoom-balancer
  labels:
    app : kubedoom-app
spec:
  selector:
    project: lesson3
  ports:
    - name      : app-vnc
      protocol  : TCP
      port      : 8888
      targetPort: 5900
  type: LoadBalancer
